### ISSUE TITLE
✨ feat: 에러 핸들러 및 API 응답 규격화

### ISSUE THREAD

**Issue by jinho7** [WaitherTeam/Waither-BE#11]
# Title

- ✨ feat: 에러 핸들러 및 API 응답 규격화

# TODO

- [x] API 응답 클래스
- [x] BaseEntity (Time 관련)
- [x] ErrorCode
- [x] 에러 핸들러 클래스
- [x] RedisConfig

# etc

- 핸들이 고장난 8t 트럭
