### ISSUE TITLE
✨ feat: 체감온도 api 연결

### ISSUE THREAD

**Issue by seheonnn** [WaitherTeam/Waither-BE#154]
# Title

- 체감온도 Kafka 연결

# TODO

- [x] 체감온도 변환 로직 구현
- [x] ~~체감온도 Kafka 연결~~
- [x] 체감온도 api 연결

# etc

- 어쩌구저쩌구
