### ISSUE TITLE
✨ feat: 사용자 설정 API

### ISSUE THREAD

**Issue by jinho7** [WaitherTeam/Waither-BE#33]
# Title

- ✨ feat: 사용자 설정 API

# TODO

- [x] 사용자 설정 - 사용자 맞춤 서비스 제공
- [x] 사용자 설정 - 메인 화면 날씨 상세 정보
- [x] 사용자 설정 - 알림 설정
- [x] 사용자 설정 - 알림 세부 설정
- [x] 사용자 설정 - 바람세기 예보
- [x] 사용자 설정 - 이름 설정
- [x] 사용자 설정 - 비밀번호 확인
- [x] 사용자 설정 - 비밀번호 재설정
- [x] 사용자 설정 - 회원 탈퇴
- [x] 사용자 설정 - 직장 지역 설정
- [x] 사용자 설정 - 직장 지역 위치 설정
- [x] 사용자 설정 - 사용자 데이터 설정
- [x] 사용자 설정 - 사용자 맞춤 서비스 제공 조회
- [x] 사용자 설정 - 메인 화면 날씨 상세 정보 조회
- [x] 사용자 설정 - 알림 설정 조회
- [x] 사용자 설정 - 바람세기 예보 조회
- [x] 사용자 설정 - 개인정보 조회
- [x] 사용자 설정 - 직장 지역 설정 조회

# etc

- 어쩌구저쩌구
