### ISSUE TITLE
💚 ci/cd: 배포 환경 구축

### ISSUE THREAD

**Issue by DDonghyeo** [WaitherTeam/Waither-BE#61]
# Title

- CI/CD 배포 파이프라인 구축

# TODO

- [x] 빌드 테스트 (CI) 스크립트 작성
- [x] docker-compose 작성
- [x] common.sh / docker_init.sh / deploy.sh 작성
- [x] AWS EC2, RDS 생성과 연결
- [x] Private Key, 쉘 스크립트, docker-compose 주입
- [x] CI/CD 스크립트 작성
- [x] 각 서비스 Dockerfile생성
- [x] 각 서비스 jar disabled
- [x] api-Gateway 포트 80으로 변경(임시)
